// Generated by dts-bundle-generator v9.5.1

/**
 * The packet types, defined by the firmware
 */
export declare enum PacketType {
	PING = 0,
	GET_CONFIG = 1,
	SET_CONFIG = 2,
	SET_LEDS = 3,
	RESET_WIFI = 4,
	GET_INFO = 5,
	GET_STATUS = 6
}
/** Serialized as: [pin, num_leds, port_h, port_l, hostname...] */
export type Config = {
	hostname: string;
	port: number;
	pin: number;
	num_leds: number;
};
/** A bare IP, as dotted string or 4 octets. `address` is reserved for the combined ip+port form. */
export type IP = string | [
	number,
	number,
	number,
	number
];
/** Device identity. Serialized as: [ip(4), port(2), mac(6), version_len(1), version, hostname_len(1), hostname] */
export type DeviceInfo = {
	ip: string;
	port: number;
	mac: string;
	version: string;
	hostname: string;
};
/** Device status. Serialized as: [uptime(4), heap(4), rssi(1), metrics?(32), debug?(48)] */
export type Status = {
	uptime: number;
	heap: number;
	rssi: number;
	internalHeap?: number;
	largestHeapBlock?: number;
	minHeap?: number;
	framesReceived?: number;
	framesShown?: number;
	framesDropped?: number;
	udpPacketsRead?: number;
	protocolLoopMaxGapMs?: number;
	arrivalGapHist?: number[];
	arrivalGapMaxMs?: number;
	arrivalGapMaxAgeS?: number;
	seqLost?: number;
	seqReordered?: number;
	beaconTimeouts?: number;
	wifiDisconnects?: number;
};
/**
 * Canvas-to-LED sampling.
 */
export type WhiteChannel = number | boolean | ((r: number, g: number, b: number) => number);
export type Polygon = [
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number
];
/**
 * Samples a canvas frame onto a straight LED strip.
 *
 * The strip is a single line running from the polygon's start edge (TL→TR) to
 * its end edge (BL→BR), sampled along the centerline: for each LED `i` the
 * source pixel under its point is read via bilinear interpolation of the
 * quadrilateral, and `[r, g, b, w]` is written into `output`. The
 * polygon's width doesn't matter — only the centerline is read. To run the
 * strip horizontally, rotate the polygon (start edge on the left). Skewed,
 * rotated or perspective-distorted polygons all work — the sampling follows
 * the quad.
 *
 * @param pixels source pixels (RGBA, 4 bytes per pixel)
 * @param pixelsSize source image size [width, height] in pixels
 * @param grid how the source image is divided [cols, rows] — defines cell size
 * @param polygon region of the grid to map onto the LEDs [TL, TR, BR, BL] as (x0,y0, x1,y1, x2,y2, x3,y3) in grid coordinates
 * @param steps number of LEDs
 * @param wa white/brightness channel: fixed number, true = use source alpha, or a function(r,g,b) => w
 * @param output output buffer [r, g, b, w, ...] — allocated automatically if not provided
 */
export declare function sample(pixels: Uint8Array, pixelsSize: [
	number,
	number
], grid: [
	number,
	number
], polygon: Polygon, steps: number, wa?: WhiteChannel, output?: Uint8Array<ArrayBuffer>): Uint8Array;
/** Register a callback for connection state changes, returns an unsubscribe function */
export declare function onConnectionChange(callback: (connected: boolean) => void): () => void;
/** Return the current WebSocket connection state */
export declare function isConnected(): boolean;
/** Runtime LED device handle for the client. */
export type Device = {
	config: Config;
	send: (leds: Uint8Array, startIndex?: number) => void;
	sendRaw: (type: PacketType, data?: Uint8Array) => void;
	sendRawSync: (type: PacketType, data?: Uint8Array) => Promise<Uint8Array>;
};
/** Connect to the proxy server. Must be called before any other function. */
export declare function begin(serverURL: string, debug?: boolean): Promise<boolean>;
/** Send a ping to the device and wait for the response. */
export declare function ping(ip: IP, port?: number): Promise<boolean>;
/** Get the configuration of the device. */
export declare function getConfig(ip: IP, port?: number): Promise<Config | null>;
/** Get device identity: IP, port, MAC, hostname and firmware version. */
export declare function getInfo(ip: IP, port?: number): Promise<DeviceInfo | null>;
/** Get device status: uptime, heap, WiFi RSSI and optional metrics. */
export declare function getStatus(ip: IP, port?: number): Promise<Status | null>;
/** Send LED colors to the device — fire-and-forget, no response expected. */
export declare function setLEDs(ip: IP, port: number | undefined, leds: Uint8Array, startIndex?: number): void;
/** Ping the device and fetch its config. Returns null if unreachable. */
export declare function connect(ip: IP, port?: number): Promise<Device | null>;
/**
 * Send a raw protocol packet — any PacketType, fire-and-forget.
 * Escape hatch for the packet types the high-level API doesn't wrap
 * (e.g. SET_CONFIG, RESET_WIFI). For request/response types use sendRawSync.
 */
export declare function sendRaw(ip: IP, port: number, type: PacketType, data?: Uint8Array): void;
/**
 * Send a raw protocol packet and wait for the response payload as relayed by
 * the proxy: `[status]` for status-only replies (1 = OK), or the response
 * data (e.g. the info payload bytes for GET_INFO).
 */
export declare function sendRawSync(ip: IP, port: number, type: PacketType, data?: Uint8Array): Promise<Uint8Array>;
declare const reactiveLeds: {
	begin: typeof begin;
	onConnectionChange: typeof onConnectionChange;
	isConnected: typeof isConnected;
	connect: typeof connect;
	ping: typeof ping;
	getInfo: typeof getInfo;
	getConfig: typeof getConfig;
	getStatus: typeof getStatus;
	setLEDs: typeof setLEDs;
	sendRaw: typeof sendRaw;
	sendRawSync: typeof sendRawSync;
	sample: typeof sample;
	PacketType: typeof PacketType;
};

export {
	reactiveLeds as default,
};

export {};
