// Generated by dts-bundle-generator v9.5.1

/** Serialized as: [pin, num_leds, port_h, port_l, hostname...] */
export type Config = {
	hostname: string;
	port: number;
	pin: number;
	num_leds: number;
};
export type DeviceIP = string | [
	number,
	number,
	number,
	number
];
/** Device status: uptime, free heap, WiFi RSSI. Serialized as: [uptime(4), heap(4), rssi(1)] */
export type Status = {
	uptime: number;
	heap: number;
	rssi: number;
};
/**
 * Utility functions for mapping pixels to LEDs
 */
/**
 * Maps pixels from a source image to a LED strip arranged in a 2D serpentine grid.
 *
 * The strip is treated as a grid of `ledCols x ledRows` LEDs, where the number of
 * columns and rows is derived from the physical aspect ratio of the polygon.
 * Odd rows are wired right-to-left (serpentine), matching the physical layout of LED panels.
 *
 * The polygon maps a region of the source grid to the LED layout using bilinear
 * interpolation, so it works correctly even for skewed or rotated quadrilaterals.
 *
 * @param pixels source pixels (RGBA, 4 bytes per pixel)
 * @param pixelsSize source image size [width, height] in pixels
 * @param grid how the source image is divided [cols, rows] — defines cell size
 * @param polygon region of the grid to map onto the LEDs [TL, TR, BR, BL] as (x0,y0, x1,y1, x2,y2, x3,y3) in grid coordinates
 * @param steps number of LEDs
 * @param wa white/brightness channel: fixed number, true = use source alpha, or a function(r,g,b) => w
 * @param output output buffer [led_index, r, g, b, w, ...] — allocated automatically if not provided
 */
export declare function mapPixels(pixels: Uint8Array, pixelsSize: [
	number,
	number
], grid: [
	number,
	number
], polygon: [
	number,
	number,
	number,
	number,
	number,
	number,
	number,
	number
], steps: number, wa?: number | boolean | ((r: number, g: number, b: number) => number), output?: Uint8Array<ArrayBuffer>): Uint8Array;
/** Register a callback for connection state changes, returns an unsubscribe function */
export declare function onConnectionChange(callback: (connected: boolean) => void): (() => void) | undefined;
/** Return the current WebSocket connection state */
export declare function isConnected(): boolean;
/** Runtime LED device handle for the client. */
export type Device = {
	config: Config;
	send: (leds: Uint8Array) => void;
};
/** Connect to the proxy server. Must be called before any other function. */
export declare function begin(serverURL: string, debug?: boolean): Promise<boolean>;
/** Send a ping to the device and wait for the response. */
export declare function ping(address: DeviceIP, port?: number): Promise<boolean>;
/** Get the configuration of the device. */
export declare function getConfig(address: DeviceIP, port?: number): Promise<Config | null>;
/** Get device status: uptime (seconds), free heap (bytes), WiFi RSSI (dBm). */
export declare function getStatus(address: DeviceIP, port?: number): Promise<Status | null>;
/** Send LED colors to the device — fire-and-forget, no response expected. */
export declare function setLEDs(address: DeviceIP, port: number | undefined, leds: Uint8Array): void;
/** Ping the device and fetch its config. Returns null if unreachable. */
export declare function connect(address: DeviceIP, port?: number): Promise<Device | null>;
declare const reactiveLeds: {
	begin: typeof begin;
	onConnectionChange: typeof onConnectionChange;
	isConnected: typeof isConnected;
	connect: typeof connect;
	ping: typeof ping;
	getConfig: typeof getConfig;
	getStatus: typeof getStatus;
	setLEDs: typeof setLEDs;
	mapPixels: typeof mapPixels;
};

export {
	reactiveLeds as default,
};

export {};
